import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Supervisor
 */
public class ClientSideGUIFinal extends javax.swing.JFrame {

    /** IDK */
	private static final long serialVersionUID = 1L;
	
	public ClientSide client;
    public int hashName;
    boolean draw = true;
    int onHex;
    
    /**
     * Creates new form ClientSideGUIFinal
     */
    public ClientSideGUIFinal(ClientSide client, int hashName, int[] map) {
    	this(client, hashName);
    	setupAllHexs(map);
    }
    
    public ClientSideGUIFinal(ClientSide client, int hashName) {
        this();
        this.client = client;
        this.hashName = hashName;
        this.setVisible(true);
    }
    
    public ClientSideGUIFinal() {
        initComponents();
        addHexListeners();
    }
    
    public void addHexListeners() {
        for (int i = 0; i < allHexs.length; i++) {
        	onHex = i;
        	if (allHexs[i] == null) { return; }
            allHexs[i].addMouseListener(new MouseListener() {

            	int thisHex = onHex;
            	
				@Override
				public void mouseClicked(MouseEvent e) {
					if (e.getClickCount() == 2 & !e.isConsumed()) {
						Request theRequest = new Request();
						theRequest.setRequest(11);
						theRequest.setHexagonSelected(thisHex);
						sendRequest(theRequest);
					}
					
				}

				@Override
				public void mouseEntered(MouseEvent arg0) {
					// TODO Show all players which have this slot
					
				}

				@Override
				public void mouseExited(MouseEvent arg0) {
					// TODO Stop showing all players who have this slot
					
				}

				@Override
				public void mousePressed(MouseEvent arg0) {	}

				@Override
				public void mouseReleased(MouseEvent arg0) { }
                
            });
        }
    }
    
    public void updateResourceNumber(int[] numOfEachCard) {
    	for (int i = 0; i < allStatsLabel.length; i++) {
    		System.out.println("Updating " + i + " and original text was " + allStatsLabel[i].getText());
    		allStatsLabel[i].setText("" + numOfEachCard[i]);
    	}
    	repaint();
    }
    
    public void updateDieRolled(int[] dieRolled) {
    	dieRollOne.setText("" + dieRolled[0]);
    	dieRollTwo.setText("" + dieRolled[1]);
    }
    
    public void setupAllHexs(int[] attributeOfHex) {
    	for (int i = 0; i < allHexs.length; i++) {
    		System.out.println("Setting up hex " + i);
    		setupIndividualHex(allHexs[i], attributeOfHex[i]);
    	}
    }
    
    public void setupIndividualHex(PaintImage hexToSetup, int type) {
    	String logo = "";
    	switch (type) {
    		case -1: logo = "desertHexLogo"; break;
    		case 0: logo = "woodHexLogo"; break;
    		case 1: logo = "sheepHexLogo"; break;
    		case 2: logo = "brickHexLogo"; break;
    		case 3: logo = "rockHexLogo"; break;
    		case 4: logo = "wheatHexLogo"; break;
    		default: System.out.println("Someone is trying to hack the game."); System.exit(-100); break;
    	}
    	hexToSetup.setImage("images/" + logo);
    }
    
    public void setTurnCheckBox(boolean selected) {
    	turnCheckBox.setSelected(selected);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        new javax.swing.JPanel();
        hex4 = new PaintImage();
        hex0 = new PaintImage();
        hex9 = new PaintImage();
        hex14 = new PaintImage();
        hex18 = new PaintImage();
        hex2 = new PaintImage();
        hex7 = new PaintImage();
        hex12 = new PaintImage();
        hex17 = new PaintImage();
        hex16 = new PaintImage();
        hex1 = new PaintImage();
        hex11 = new PaintImage();
        hex6 = new PaintImage();
        hex5 = new PaintImage();
        hex10 = new PaintImage();
        hex15 = new PaintImage();
        hex8 = new PaintImage();
        hex3 = new PaintImage();
        hex13 = new PaintImage();
        new javax.swing.JPanel();
        new javax.swing.JPanel();
        chatLogScrollPane = new javax.swing.JScrollPane();
        chatLogPanel = new javax.swing.JTextArea();
        nextTurnButton = new javax.swing.JButton();
        sendMessageButton = new javax.swing.JButton();
        chatTextFieldScrollPane = new javax.swing.JScrollPane();
        chatTextField = new javax.swing.JTextArea();
        cardPanel = new javax.swing.JPanel();
        woodLogoPanel = new PaintImage("images/woodLogo");
        woodNumberLabel = new javax.swing.JLabel();
        sheepLogoPanel = new PaintImage("images/sheepLogo");
        sheepNumberLabel = new javax.swing.JLabel();
        brickLogoPanel = new PaintImage("images/brickLogo");
        brickNumberLabel = new javax.swing.JLabel();
        rockLogoPanel = new PaintImage("images/rockLogo");
        rockNumberLabel = new javax.swing.JLabel();
        wheatLogoPanel = new PaintImage("images/wheatLogo");
        wheatNumberLabel = new javax.swing.JLabel();
        devCardLogoPanel = new PaintImage("images/devCardLogo");
        devCardNumberLabel = new javax.swing.JLabel();
        woodDrawButton = new javax.swing.JButton();
        sheepDrawButton = new javax.swing.JButton();
        brickDrawButton = new javax.swing.JButton();
        rockDrawButton = new javax.swing.JButton();
        wheatDrawButton = new javax.swing.JButton();
        devCardDrawButton = new javax.swing.JButton();
        turnCheckBox = new javax.swing.JCheckBox();
        statsOfPlayers = new javax.swing.JButton();
        changeDrawButton = new javax.swing.JToggleButton();
        rollDiceButton = new javax.swing.JButton();

        allHexs = new PaintImage[] { hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7, hex8, hex9, hex10, hex11, hex12, hex13, hex14, hex15, hex16, hex17, hex18 };
        allStatsLabel = new javax.swing.JLabel[] { woodNumberLabel, sheepNumberLabel, brickNumberLabel, rockNumberLabel, wheatNumberLabel };
        
        dieRollOne = new javax.swing.JLabel();
        dieRollTwo = new javax.swing.JLabel();
        
        new javax.swing.JPanel();
        new javax.swing.JPanel();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        chatLogPanel.setColumns(20);
        chatLogPanel.setRows(5);
        chatLogScrollPane.setViewportView(chatLogPanel);

        nextTurnButton.setText("End Turn");
        nextTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnButtonActionPerformed(evt);
            }
        });

        sendMessageButton.setText("Send");

        chatTextField.setColumns(20);
        chatTextField.setRows(5);
        chatTextFieldScrollPane.setViewportView(chatTextField);

        woodNumberLabel.setForeground(new java.awt.Color(255, 0, 0));
        woodNumberLabel.setText("jLabel1");

        javax.swing.GroupLayout woodLogoPanelLayout = new javax.swing.GroupLayout(woodLogoPanel);
        woodLogoPanel.setLayout(woodLogoPanelLayout);
        woodLogoPanelLayout.setHorizontalGroup(
            woodLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(woodLogoPanelLayout.createSequentialGroup()
                .addComponent(woodNumberLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        woodLogoPanelLayout.setVerticalGroup(
            woodLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(woodLogoPanelLayout.createSequentialGroup()
                .addComponent(woodNumberLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        sheepNumberLabel.setForeground(new java.awt.Color(51, 255, 0));
        sheepNumberLabel.setText("jLabel2");

        javax.swing.GroupLayout sheepLogoPanelLayout = new javax.swing.GroupLayout(sheepLogoPanel);
        sheepLogoPanel.setLayout(sheepLogoPanelLayout);
        sheepLogoPanelLayout.setHorizontalGroup(
            sheepLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sheepLogoPanelLayout.createSequentialGroup()
                .addComponent(sheepNumberLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sheepLogoPanelLayout.setVerticalGroup(
            sheepLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sheepLogoPanelLayout.createSequentialGroup()
                .addComponent(sheepNumberLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        brickNumberLabel.setForeground(new java.awt.Color(0, 0, 204));
        brickNumberLabel.setText("jLabel3");

        javax.swing.GroupLayout brickLogoPanelLayout = new javax.swing.GroupLayout(brickLogoPanel);
        brickLogoPanel.setLayout(brickLogoPanelLayout);
        brickLogoPanelLayout.setHorizontalGroup(
            brickLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brickLogoPanelLayout.createSequentialGroup()
                .addComponent(brickNumberLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        brickLogoPanelLayout.setVerticalGroup(
            brickLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brickLogoPanelLayout.createSequentialGroup()
                .addComponent(brickNumberLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        rockNumberLabel.setForeground(new java.awt.Color(255, 0, 0));
        rockNumberLabel.setText("jLabel8");

        javax.swing.GroupLayout rockLogoPanelLayout = new javax.swing.GroupLayout(rockLogoPanel);
        rockLogoPanel.setLayout(rockLogoPanelLayout);
        rockLogoPanelLayout.setHorizontalGroup(
            rockLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockLogoPanelLayout.createSequentialGroup()
                .addComponent(rockNumberLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rockLogoPanelLayout.setVerticalGroup(
            rockLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockLogoPanelLayout.createSequentialGroup()
                .addComponent(rockNumberLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        wheatNumberLabel.setForeground(new java.awt.Color(0, 204, 0));
        wheatNumberLabel.setText("jLabel9");

        javax.swing.GroupLayout wheatLogoPanelLayout = new javax.swing.GroupLayout(wheatLogoPanel);
        wheatLogoPanel.setLayout(wheatLogoPanelLayout);
        wheatLogoPanelLayout.setHorizontalGroup(
            wheatLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheatLogoPanelLayout.createSequentialGroup()
                .addComponent(wheatNumberLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        wheatLogoPanelLayout.setVerticalGroup(
            wheatLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheatLogoPanelLayout.createSequentialGroup()
                .addComponent(wheatNumberLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        devCardNumberLabel.setForeground(new java.awt.Color(0, 0, 204));
        devCardNumberLabel.setText("0");

        javax.swing.GroupLayout devCardLogoPanelLayout = new javax.swing.GroupLayout(devCardLogoPanel);
        devCardLogoPanel.setLayout(devCardLogoPanelLayout);
        devCardLogoPanelLayout.setHorizontalGroup(
            devCardLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devCardLogoPanelLayout.createSequentialGroup()
                .addComponent(devCardNumberLabel)
                .addGap(0, 112, Short.MAX_VALUE))
        );
        devCardLogoPanelLayout.setVerticalGroup(
            devCardLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devCardLogoPanelLayout.createSequentialGroup()
                .addComponent(devCardNumberLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        woodDrawButton.setText("Lumber");
        woodDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                woodDrawButtonActionPerformed(evt);
            }
        });

        sheepDrawButton.setText("Sheep");
        sheepDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sheepDrawButtonActionPerformed(evt);
            }
        });

        brickDrawButton.setText("Brick");
        brickDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brickDrawButtonActionPerformed(evt);
            }
        });

        rockDrawButton.setText("Rock");
        rockDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockDrawButtonActionPerformed(evt);
            }
        });

        wheatDrawButton.setText("Wheat");
        wheatDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheatDrawButtonActionPerformed(evt);
            }
        });

        devCardDrawButton.setText("Development Card");
        devCardDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devCardDrawButtonActionPerformed(evt);
            }
        });

        turnCheckBox.setText("My Turn");
        turnCheckBox.setEnabled(false);

        statsOfPlayers.setText("Get Stats of Others");

        changeDrawButton.setText("Remove");
        changeDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDrawButtonActionPerformed(evt);
            }
        });

        rollDiceButton.setText("Roll Dice");
        rollDiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollDiceButtonActionPerformed(evt);
            }
        });

        dieRollOne.setText("1");

        dieRollTwo.setText("1");

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turnCheckBox)
                    .addGroup(cardPanelLayout.createSequentialGroup()
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rollDiceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(woodDrawButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(woodLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardPanelLayout.createSequentialGroup()
                                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sheepLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sheepDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(brickLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(brickDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rockDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(rockLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(wheatLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(wheatDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addGroup(cardPanelLayout.createSequentialGroup()
                                .addComponent(dieRollOne, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dieRollTwo)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(devCardDrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devCardLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeDrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statsOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(rockLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brickLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(devCardLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wheatLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sheepLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(woodLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(woodDrawButton)
                    .addComponent(sheepDrawButton)
                    .addComponent(brickDrawButton)
                    .addComponent(rockDrawButton)
                    .addComponent(wheatDrawButton)
                    .addComponent(devCardDrawButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnCheckBox)
                    .addComponent(changeDrawButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsOfPlayers)
                    .addComponent(rollDiceButton)
                    .addComponent(dieRollOne)
                    .addComponent(dieRollTwo))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout hex4Layout = new javax.swing.GroupLayout(hex4);
        hex4.setLayout(hex4Layout);
        hex4Layout.setHorizontalGroup(
            hex4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex4Layout.setVerticalGroup(
            hex4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex0Layout = new javax.swing.GroupLayout(hex0);
        hex0.setLayout(hex0Layout);
        hex0Layout.setHorizontalGroup(
            hex0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex0Layout.setVerticalGroup(
            hex0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex9Layout = new javax.swing.GroupLayout(hex9);
        hex9.setLayout(hex9Layout);
        hex9Layout.setHorizontalGroup(
            hex9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex9Layout.setVerticalGroup(
            hex9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex14Layout = new javax.swing.GroupLayout(hex14);
        hex14.setLayout(hex14Layout);
        hex14Layout.setHorizontalGroup(
            hex14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex14Layout.setVerticalGroup(
            hex14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex18Layout = new javax.swing.GroupLayout(hex18);
        hex18.setLayout(hex18Layout);
        hex18Layout.setHorizontalGroup(
            hex18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex18Layout.setVerticalGroup(
            hex18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex2Layout = new javax.swing.GroupLayout(hex2);
        hex2.setLayout(hex2Layout);
        hex2Layout.setHorizontalGroup(
            hex2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex2Layout.setVerticalGroup(
            hex2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex7Layout = new javax.swing.GroupLayout(hex7);
        hex7.setLayout(hex7Layout);
        hex7Layout.setHorizontalGroup(
            hex7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex7Layout.setVerticalGroup(
            hex7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex12Layout = new javax.swing.GroupLayout(hex12);
        hex12.setLayout(hex12Layout);
        hex12Layout.setHorizontalGroup(
            hex12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex12Layout.setVerticalGroup(
            hex12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex17Layout = new javax.swing.GroupLayout(hex17);
        hex17.setLayout(hex17Layout);
        hex17Layout.setHorizontalGroup(
            hex17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex17Layout.setVerticalGroup(
            hex17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex16Layout = new javax.swing.GroupLayout(hex16);
        hex16.setLayout(hex16Layout);
        hex16Layout.setHorizontalGroup(
            hex16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex16Layout.setVerticalGroup(
            hex16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex1Layout = new javax.swing.GroupLayout(hex1);
        hex1.setLayout(hex1Layout);
        hex1Layout.setHorizontalGroup(
            hex1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex1Layout.setVerticalGroup(
            hex1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex11Layout = new javax.swing.GroupLayout(hex11);
        hex11.setLayout(hex11Layout);
        hex11Layout.setHorizontalGroup(
            hex11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex11Layout.setVerticalGroup(
            hex11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex6Layout = new javax.swing.GroupLayout(hex6);
        hex6.setLayout(hex6Layout);
        hex6Layout.setHorizontalGroup(
            hex6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex6Layout.setVerticalGroup(
            hex6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex5Layout = new javax.swing.GroupLayout(hex5);
        hex5.setLayout(hex5Layout);
        hex5Layout.setHorizontalGroup(
            hex5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex5Layout.setVerticalGroup(
            hex5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex10Layout = new javax.swing.GroupLayout(hex10);
        hex10.setLayout(hex10Layout);
        hex10Layout.setHorizontalGroup(
            hex10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex10Layout.setVerticalGroup(
            hex10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex15Layout = new javax.swing.GroupLayout(hex15);
        hex15.setLayout(hex15Layout);
        hex15Layout.setHorizontalGroup(
            hex15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex15Layout.setVerticalGroup(
            hex15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex8Layout = new javax.swing.GroupLayout(hex8);
        hex8.setLayout(hex8Layout);
        hex8Layout.setHorizontalGroup(
            hex8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex8Layout.setVerticalGroup(
            hex8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex3Layout = new javax.swing.GroupLayout(hex3);
        hex3.setLayout(hex3Layout);
        hex3Layout.setHorizontalGroup(
            hex3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex3Layout.setVerticalGroup(
            hex3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex13Layout = new javax.swing.GroupLayout(hex13);
        hex13.setLayout(hex13Layout);
        hex13Layout.setHorizontalGroup(
            hex13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex13Layout.setVerticalGroup(
            hex13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hex3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hex11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hex0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hex12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hex10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatLogScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nextTurnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chatTextFieldScrollPane)))
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chatLogScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatTextFieldScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hex0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hex5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hex3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hex13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendMessageButton)
                    .addComponent(nextTurnButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void brickDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(2);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }                                               

    private void woodDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(0);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }                                              

    private void sheepDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(1);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }                                               

    private void rockDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(3);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }                                              

    private void wheatDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(4);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }                                               

    private void devCardDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        Request theRequest = new Request();
        theRequest.setRequest(1);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }                                                 

    private void changeDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        draw = !draw;
        // TODO add your handling code here:
    }                                                

    private void nextTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Request theRequest = new Request();
        theRequest.setRequest(5);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }                                              

    private void rollDiceButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Request theRequest = new Request();
        theRequest.setRequest(2);
        sendRequest(theRequest);        
        // TODO add your handling code here:
    }                                              

    private void sendRequest(Request request) {
        client.sendRequest(request);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton brickDrawButton;
    private javax.swing.JLabel brickNumberLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JToggleButton changeDrawButton;
    private javax.swing.JTextArea chatLogPanel;
    private javax.swing.JScrollPane chatLogScrollPane;
    private javax.swing.JTextArea chatTextField;
    private javax.swing.JScrollPane chatTextFieldScrollPane;
    private javax.swing.JButton devCardDrawButton;
    private javax.swing.JLabel devCardNumberLabel;
    private javax.swing.JButton nextTurnButton;
    private javax.swing.JButton rockDrawButton;
    private javax.swing.JLabel rockNumberLabel;
    private javax.swing.JButton rollDiceButton;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JButton sheepDrawButton;
    private javax.swing.JLabel sheepNumberLabel;
    private javax.swing.JButton statsOfPlayers;
    private javax.swing.JCheckBox turnCheckBox;
    private javax.swing.JButton wheatDrawButton;
    private javax.swing.JLabel wheatNumberLabel;
    private javax.swing.JButton woodDrawButton;
    private javax.swing.JLabel woodNumberLabel;
    // End of variables declaration                   

     private PaintImage brickLogoPanel;
     private PaintImage devCardLogoPanel;
     private PaintImage rockLogoPanel;
     private PaintImage sheepLogoPanel;
     private PaintImage wheatLogoPanel;
     private PaintImage woodLogoPanel;
     private PaintImage hex0;
     private PaintImage hex1;
     private PaintImage hex2;
     private PaintImage hex3;
     private PaintImage hex4;
     private PaintImage hex5;
     private PaintImage hex6;
     private PaintImage hex7;
     private PaintImage hex8;
     private PaintImage hex9;
     private PaintImage hex10;
     private PaintImage hex11;
     private PaintImage hex12;
     private PaintImage hex13;
     private PaintImage hex14;
     private PaintImage hex15;
     private PaintImage hex16;
     private PaintImage hex17;
     private PaintImage hex18;
     private PaintImage[] allHexs;
     private javax.swing.JLabel[] allStatsLabel;
     private javax.swing.JLabel dieRollOne;
     private javax.swing.JLabel dieRollTwo;
    
    
}

class PaintImage extends JPanel {

	/** IDK */
	private static final long serialVersionUID = 1L;

	public BufferedImage image; 

	public PaintImage() {
		image = null;
	}

	public PaintImage (String imageName) 
	{ 
		super(); 
		try 
		{                
			image = ImageIO.read(new File(imageName)); 
		} 
		catch (IOException e) 
		{ 
			System.out.println("Fail.");
			//Not handled.
		}
	}

	public void setImage(String filename) {
		try { image = ImageIO.read(new File(filename)); }
		catch (Exception e) { System.out.println("Fail."); }
	}

	public void paintComponent(Graphics g) 
	{
		g.drawImage(image, 0, 0, null); 
		repaint(); 
	}


}

class PopUpStats extends javax.swing.JFrame {

	/** IDK */
	private static final long serialVersionUID = 1L;
	ClientSide client;
	int hexagon;
	int settlement = -1;
	int road = -1;

	/**
	 * Creates new form popupstatstesting
	 */
	public PopUpStats(int hexagon, String[] roadStats, String[] settlementStats, ClientSide client) {
		this(roadStats, settlementStats, client);
		this.hexagon = hexagon;
	}

	public PopUpStats(String[] roadStats, String[] settlementStats, ClientSide client) {
		this(roadStats, settlementStats);
		this.client = client;
	}

	public PopUpStats(String[] roadStats, String[] settlementStats) {
		this();
		setupStats(roadStats, settlementStats);
	}

	public PopUpStats() {
		initComponents();
	}

	public void setupStats(String[] roadStats, String[] settlementStats) {
		for (int i = 0; i < roads.length; i++) {
			roads[i].setText(roadStats[i]);
		}
    	for (int i = 0; i < roads.length; i++) {
    		settlements[i].setText(settlementStats[i]);
    	}
    }
    
    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	if (road == -1 && settlement == -1) { return; }
    	Request toSend = new Request();
    	toSend.setRequest(road == -1 ? 7 : 8);
    	toSend.setHexagonSelected(hexagon);
    	if (road == -1) { toSend.setOnSpotSelected(settlement); }
    	else if (settlement == -1) { toSend.setRoadsSpotSelected(road); }
    	sendRequest(toSend);
    	road = -1; settlement = -1;
        // TODO add your handling code here:
    }

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	if (road == -1 && settlement == -1) { return; }
    	Request toSend = new Request();
    	toSend.setRequest(road == -1 ? 9 : 10);
    	toSend.setHexagonSelected(hexagon);
    	if (road == -1) { toSend.setOnSpotSelected(settlement); }
    	else if (settlement == -1) { toSend.setRoadsSpotSelected(road); }
    	System.out.println("You just removed something.");
    	sendRequest(toSend);
    	road = -1; settlement = -1;
        // TODO add your handling code here:
    }
    
    private void sendRequest(Request request) {
        client.sendRequest(request);
    }
    
    private void settlement1MouseClicked(java.awt.event.MouseEvent evt) {
    	road = -1;
    	settlement = 0;
    }

    private void settlement2MouseClicked(java.awt.event.MouseEvent evt) {
    	road = -1;
    	settlement = 1;
    }

    private void settlement3MouseClicked(java.awt.event.MouseEvent evt) {
    	road = -1;
    	settlement = 2;
    }

    private void settlement4MouseClicked(java.awt.event.MouseEvent evt) {
    	road = -1;
    	settlement = 3;
    }

    private void settlement5MouseClicked(java.awt.event.MouseEvent evt) {
    	road = -1;
    	settlement = 4;
    }

    private void settlement6MouseClicked(java.awt.event.MouseEvent evt) {
    	road = -1;
    	settlement = 5;
    }

    private void road1MouseClicked(java.awt.event.MouseEvent evt) {
    	settlement = -1;
    	road = 0;
    }

    private void road2MouseClicked(java.awt.event.MouseEvent evt) {
    	settlement = -1;
    	road = 1;
    }

    private void road3MouseClicked(java.awt.event.MouseEvent evt) {
    	settlement = -1;
    	road = 2;
    }

    private void road4MouseClicked(java.awt.event.MouseEvent evt) {
    	settlement = -1;
    	road = 3;
    }

    private void road5MouseClicked(java.awt.event.MouseEvent evt) {
    	settlement = -1;
    	road = 4;
    }

    private void road6MouseClicked(java.awt.event.MouseEvent evt) {
    	settlement = -1;
    	road = 5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

    	jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        settlement1 = new javax.swing.JLabel();
        settlement2 = new javax.swing.JLabel();
        settlement3 = new javax.swing.JLabel();
        settlement4 = new javax.swing.JLabel();
        settlement5 = new javax.swing.JLabel();
        settlement6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        road1 = new javax.swing.JLabel();
        road2 = new javax.swing.JLabel();
        road3 = new javax.swing.JLabel();
        road4 = new javax.swing.JLabel();
        road5 = new javax.swing.JLabel();
        road6 = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        settlements = new javax.swing.JLabel[] { settlement1, settlement2, settlement3, settlement4,settlement5, settlement6 };
        roads = new javax.swing.JLabel[] { road1, road2, road3, road4, road5, road6 };

        //TODO FIX THIS!
        //setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFont(new Font("Monospaced", Font.PLAIN, 13));
        jTextArea1.setText("   0__1                          _0_\n  5/  \\2  Settlements | Roads  5/   \\1\n   \\__/                        4\\_3_/2\n   4  3");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Settlements");

        settlement1.setText("jLabel3");
        settlement1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlement1MouseClicked(evt);
            }
        });

        settlement2.setText("jLabel4");
        settlement2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlement2MouseClicked(evt);
            }
        });

        settlement3.setText("jLabel5");
        settlement3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlement3MouseClicked(evt);
            }
        });

        settlement4.setText("jLabel6");
        settlement4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlement4MouseClicked(evt);
            }
        });

        settlement5.setText("jLabel7");
        settlement5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlement5MouseClicked(evt);
            }
        });

        settlement6.setText("jLabel8");
        settlement6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlement6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(settlement1)
                    .addComponent(settlement2)
                    .addComponent(settlement3)
                    .addComponent(settlement4)
                    .addComponent(settlement5)
                    .addComponent(settlement6))
                .addGap(0, 60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settlement1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settlement2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settlement3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settlement4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settlement5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settlement6)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Roads");

        road1.setText("jLabel9");
        road1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                road1MouseClicked(evt);
            }
        });

        road2.setText("jLabel10");
        road2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                road2MouseClicked(evt);
            }
        });

        road3.setText("jLabel11");
        road3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                road3MouseClicked(evt);
            }
        });

        road4.setText("jLabel12");
        road4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                road4MouseClicked(evt);
            }
        });

        road5.setText("jLabel13");
        road5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                road5MouseClicked(evt);
            }
        });

        road6.setText("jLabel14");
        road6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                road6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(road1)
                    .addComponent(road2)
                    .addComponent(road3)
                    .addComponent(road4)
                    .addComponent(road5)
                    .addComponent(road6))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(road1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(road2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(road3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(road4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(road5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(road6)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buyButton)
                    .addComponent(removeButton)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(buyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JButton buyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel road1;
    private javax.swing.JLabel road2;
    private javax.swing.JLabel road3;
    private javax.swing.JLabel road4;
    private javax.swing.JLabel road5;
    private javax.swing.JLabel road6;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel settlement1;
    private javax.swing.JLabel settlement2;
    private javax.swing.JLabel settlement3;
    private javax.swing.JLabel settlement4;
    private javax.swing.JLabel settlement5;
    private javax.swing.JLabel settlement6;
    private javax.swing.JLabel[] roads;
    private javax.swing.JLabel[] settlements;
    // End of variables declaration
}