import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Supervisor
 */
public class ClientSideGUI extends javax.swing.JFrame {

    public ClientSide client;
    public int hashName;
    boolean draw = true;
    
    /**
     * Creates new form ClientSideGUI
     */
    public ClientSideGUI(ClientSide client, int hashName, Map map) {
    	this(client, hashName);
    	//setupAllHexs(map);
    }
    
    public ClientSideGUI(ClientSide client, int hashName) {
        this();
        this.client = client;
        this.hashName = hashName;
        this.setVisible(true);
    }
    
    public ClientSideGUI() {
        initComponents();
        addHexListeners();
    }
    
    public void addHexListeners() {
        for (int i = 0; i < allHexs.length; i++) {
        	if (allHexs[i] == null) { return; }
            allHexs[i].addMouseListener(new MouseListener() {

				@Override
				public void mouseClicked(MouseEvent e) {
					if (e.getClickCount() == 2 & !e.isConsumed()) {
						// TODO Open window which shows stats of this hexagon
					}
					
				}

				@Override
				public void mouseEntered(MouseEvent arg0) {
					// TODO Show all players which have this slot
					
				}

				@Override
				public void mouseExited(MouseEvent arg0) {
					// TODO Stop showing all players who have this slot
					
				}

				@Override
				public void mousePressed(MouseEvent arg0) {	}

				@Override
				public void mouseReleased(MouseEvent arg0) { }
                
            });
        }
    }
    
//    public void updateResourceNumber(int[] numOfEachCard) {
//    	for (int i = 0; i < allStatsLabel.length; i++) {
//    		System.out.println("Updating " + i + " and original text was " + allStatsLabel[i].getText());
//    		allStatsLabel[i].setText("" + numOfEachCard[i]);
//    	}
//    	repaint();
//    }
    
//    public void setupAllHexs(int[] attributeOfHex) {
//    	for (int i = 0; i < allHexs.length; i++) {
//    		System.out.println("Setting up hex " + i);
//    		setupIndividualHex(allHexs[i], attributeOfHex[i]);
//    	}
//    }
    
    public void setupIndividualHex(PaintImage hexToSetup, int type) {
    	String logo = "";
    	switch (type) {
    		case -1: logo = "desertHexLogo"; break;
    		case 0: logo = "woodHexLogo"; break;
    		case 1: logo = "sheepHexLogo"; break;
    		case 2: logo = "brickHexLogo"; break;
    		case 3: logo = "rockHexLogo"; break;
    		case 4: logo = "wheatHexLogo"; break;
    		default: System.out.println("Someone is trying to hack the game."); System.exit(-100); break;
    	}
    	hexToSetup.setImage("images/" + logo);
    }
    
//    public void setupAllHexs(Map map) {
//    	Hexagon[] allSpaces = map.getAllSpaces();
//    	for (int i = 0; i < allSpaces.length; i++) {
//    		setupIndividualHex(allHexs[i], allSpaces[i].getType());
//    	}
//    }
//    
//    public void setupIndividualHex(PaintImage hexToSetup, int type) {
//    	String logo = "";
//    	switch (type) {
//    		case 0: logo = "woodHexLogo"; break;
//    		case 1: logo = "sheepHexLogo"; break;
//    		case 2: logo = "brickHexLogo"; break;
//    		case 3: logo = "rockHexLogo"; break;
//    		case 4: logo = "wheatHexLogo"; break;
//    		default: System.out.println("Someone is trying to hack the game."); System.exit(-100); break;
//    	}
//    	hexToSetup.setImage("images/" + logo);
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new javax.swing.JPanel();
        hex4 = new javax.swing.JPanel();
        hex0 = new javax.swing.JPanel();
        hex9 = new javax.swing.JPanel();
        hex14 = new javax.swing.JPanel();
        hex18 = new javax.swing.JPanel();
        hex2 = new javax.swing.JPanel();
        hex7 = new javax.swing.JPanel();
        hex12 = new javax.swing.JPanel();
        hex17 = new javax.swing.JPanel();
        hex16 = new javax.swing.JPanel();
        hex1 = new javax.swing.JPanel();
        hex11 = new javax.swing.JPanel();
        hex6 = new javax.swing.JPanel();
        hex5 = new javax.swing.JPanel();
        hex10 = new javax.swing.JPanel();
        hex15 = new javax.swing.JPanel();
        hex8 = new javax.swing.JPanel();
        hex3 = new javax.swing.JPanel();
        hex13 = new javax.swing.JPanel();
        chatLogScrollPane = new javax.swing.JScrollPane();
        chatLogPanel = new javax.swing.JTextArea();
        nextTurnButton = new javax.swing.JButton();
        sendMessageButton = new javax.swing.JButton();
        chatTextFieldScrollPane = new javax.swing.JScrollPane();
        chatTextField = new javax.swing.JTextArea();
        cardPanel = new javax.swing.JPanel();
        woodLogoPanel = new javax.swing.JPanel();
        woodNumberLabel = new javax.swing.JLabel();
        sheepLogoPanel = new javax.swing.JPanel();
        sheepNumberLabel = new javax.swing.JLabel();
        brickLogoPanel = new javax.swing.JPanel();
        brickNumberLabel = new javax.swing.JLabel();
        rockLogoPanel = new javax.swing.JPanel();
        rockNumberLabel = new javax.swing.JLabel();
        wheatLogoPanel = new javax.swing.JPanel();
        wheatNumberLabel = new javax.swing.JLabel();
        devCardLogoPanel = new javax.swing.JPanel();
        devCardNumberLabel = new javax.swing.JLabel();
        woodDrawButton = new javax.swing.JButton();
        sheepDrawButton = new javax.swing.JButton();
        brickDrawButton = new javax.swing.JButton();
        rockDrawButton = new javax.swing.JButton();
        wheatDrawButton = new javax.swing.JButton();
        devCardDrawButton = new javax.swing.JButton();
        turnCheckBox = new javax.swing.JCheckBox();
        statsOfPlayers = new javax.swing.JButton();
        changeDrawButton = new javax.swing.JToggleButton();
        rollDiceButton = new javax.swing.JButton();
        dieRollOne = new javax.swing.JLabel();
        dieRollTwo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout hex4Layout = new javax.swing.GroupLayout(hex4);
        hex4.setLayout(hex4Layout);
        hex4Layout.setHorizontalGroup(
            hex4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex4Layout.setVerticalGroup(
            hex4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex0Layout = new javax.swing.GroupLayout(hex0);
        hex0.setLayout(hex0Layout);
        hex0Layout.setHorizontalGroup(
            hex0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex0Layout.setVerticalGroup(
            hex0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex9Layout = new javax.swing.GroupLayout(hex9);
        hex9.setLayout(hex9Layout);
        hex9Layout.setHorizontalGroup(
            hex9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex9Layout.setVerticalGroup(
            hex9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex14Layout = new javax.swing.GroupLayout(hex14);
        hex14.setLayout(hex14Layout);
        hex14Layout.setHorizontalGroup(
            hex14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex14Layout.setVerticalGroup(
            hex14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex18Layout = new javax.swing.GroupLayout(hex18);
        hex18.setLayout(hex18Layout);
        hex18Layout.setHorizontalGroup(
            hex18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex18Layout.setVerticalGroup(
            hex18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex2Layout = new javax.swing.GroupLayout(hex2);
        hex2.setLayout(hex2Layout);
        hex2Layout.setHorizontalGroup(
            hex2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex2Layout.setVerticalGroup(
            hex2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex7Layout = new javax.swing.GroupLayout(hex7);
        hex7.setLayout(hex7Layout);
        hex7Layout.setHorizontalGroup(
            hex7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex7Layout.setVerticalGroup(
            hex7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex12Layout = new javax.swing.GroupLayout(hex12);
        hex12.setLayout(hex12Layout);
        hex12Layout.setHorizontalGroup(
            hex12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex12Layout.setVerticalGroup(
            hex12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex17Layout = new javax.swing.GroupLayout(hex17);
        hex17.setLayout(hex17Layout);
        hex17Layout.setHorizontalGroup(
            hex17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex17Layout.setVerticalGroup(
            hex17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex16Layout = new javax.swing.GroupLayout(hex16);
        hex16.setLayout(hex16Layout);
        hex16Layout.setHorizontalGroup(
            hex16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex16Layout.setVerticalGroup(
            hex16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex1Layout = new javax.swing.GroupLayout(hex1);
        hex1.setLayout(hex1Layout);
        hex1Layout.setHorizontalGroup(
            hex1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex1Layout.setVerticalGroup(
            hex1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex11Layout = new javax.swing.GroupLayout(hex11);
        hex11.setLayout(hex11Layout);
        hex11Layout.setHorizontalGroup(
            hex11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex11Layout.setVerticalGroup(
            hex11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex6Layout = new javax.swing.GroupLayout(hex6);
        hex6.setLayout(hex6Layout);
        hex6Layout.setHorizontalGroup(
            hex6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex6Layout.setVerticalGroup(
            hex6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex5Layout = new javax.swing.GroupLayout(hex5);
        hex5.setLayout(hex5Layout);
        hex5Layout.setHorizontalGroup(
            hex5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex5Layout.setVerticalGroup(
            hex5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex10Layout = new javax.swing.GroupLayout(hex10);
        hex10.setLayout(hex10Layout);
        hex10Layout.setHorizontalGroup(
            hex10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex10Layout.setVerticalGroup(
            hex10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex15Layout = new javax.swing.GroupLayout(hex15);
        hex15.setLayout(hex15Layout);
        hex15Layout.setHorizontalGroup(
            hex15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex15Layout.setVerticalGroup(
            hex15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex8Layout = new javax.swing.GroupLayout(hex8);
        hex8.setLayout(hex8Layout);
        hex8Layout.setHorizontalGroup(
            hex8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex8Layout.setVerticalGroup(
            hex8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex3Layout = new javax.swing.GroupLayout(hex3);
        hex3.setLayout(hex3Layout);
        hex3Layout.setHorizontalGroup(
            hex3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hex3Layout.setVerticalGroup(
            hex3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hex13Layout = new javax.swing.GroupLayout(hex13);
        hex13.setLayout(hex13Layout);
        hex13Layout.setHorizontalGroup(
            hex13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        hex13Layout.setVerticalGroup(
            hex13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hex3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hex11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hex0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hex12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hex10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hex5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(mapPanelLayout.createSequentialGroup()
                        .addComponent(hex3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanelLayout.createSequentialGroup()
                        .addComponent(hex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanelLayout.createSequentialGroup()
                        .addComponent(hex0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanelLayout.createSequentialGroup()
                        .addComponent(hex5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanelLayout.createSequentialGroup()
                        .addComponent(hex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hex16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        chatLogPanel.setColumns(20);
        chatLogPanel.setRows(5);
        chatLogScrollPane.setViewportView(chatLogPanel);

        nextTurnButton.setText("End Turn");
        nextTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnButtonActionPerformed(evt);
            }
        });

        sendMessageButton.setText("Send");

        chatTextField.setColumns(20);
        chatTextField.setRows(5);
        chatTextFieldScrollPane.setViewportView(chatTextField);

        woodNumberLabel.setForeground(new java.awt.Color(255, 0, 0));
        woodNumberLabel.setText("jLabel1");

        javax.swing.GroupLayout woodLogoPanelLayout = new javax.swing.GroupLayout(woodLogoPanel);
        woodLogoPanel.setLayout(woodLogoPanelLayout);
        woodLogoPanelLayout.setHorizontalGroup(
            woodLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(woodLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(woodNumberLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        woodLogoPanelLayout.setVerticalGroup(
            woodLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(woodLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(woodNumberLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        sheepNumberLabel.setForeground(new java.awt.Color(51, 255, 0));
        sheepNumberLabel.setText("jLabel2");

        javax.swing.GroupLayout sheepLogoPanelLayout = new javax.swing.GroupLayout(sheepLogoPanel);
        sheepLogoPanel.setLayout(sheepLogoPanelLayout);
        sheepLogoPanelLayout.setHorizontalGroup(
            sheepLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sheepLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sheepNumberLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sheepLogoPanelLayout.setVerticalGroup(
            sheepLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sheepLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sheepNumberLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        brickNumberLabel.setForeground(new java.awt.Color(0, 0, 204));
        brickNumberLabel.setText("jLabel3");

        javax.swing.GroupLayout brickLogoPanelLayout = new javax.swing.GroupLayout(brickLogoPanel);
        brickLogoPanel.setLayout(brickLogoPanelLayout);
        brickLogoPanelLayout.setHorizontalGroup(
            brickLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brickLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brickNumberLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        brickLogoPanelLayout.setVerticalGroup(
            brickLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brickLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brickNumberLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        rockNumberLabel.setForeground(new java.awt.Color(255, 0, 0));
        rockNumberLabel.setText("jLabel8");

        javax.swing.GroupLayout rockLogoPanelLayout = new javax.swing.GroupLayout(rockLogoPanel);
        rockLogoPanel.setLayout(rockLogoPanelLayout);
        rockLogoPanelLayout.setHorizontalGroup(
            rockLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rockNumberLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rockLogoPanelLayout.setVerticalGroup(
            rockLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rockNumberLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        wheatNumberLabel.setForeground(new java.awt.Color(0, 204, 0));
        wheatNumberLabel.setText("jLabel9");

        javax.swing.GroupLayout wheatLogoPanelLayout = new javax.swing.GroupLayout(wheatLogoPanel);
        wheatLogoPanel.setLayout(wheatLogoPanelLayout);
        wheatLogoPanelLayout.setHorizontalGroup(
            wheatLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheatLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wheatNumberLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        wheatLogoPanelLayout.setVerticalGroup(
            wheatLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wheatLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wheatNumberLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        devCardNumberLabel.setForeground(new java.awt.Color(0, 0, 204));
        devCardNumberLabel.setText("jLabel10");

        javax.swing.GroupLayout devCardLogoPanelLayout = new javax.swing.GroupLayout(devCardLogoPanel);
        devCardLogoPanel.setLayout(devCardLogoPanelLayout);
        devCardLogoPanelLayout.setHorizontalGroup(
            devCardLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devCardLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(devCardNumberLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        devCardLogoPanelLayout.setVerticalGroup(
            devCardLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devCardLogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(devCardNumberLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        woodDrawButton.setText("Wood");
        woodDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                woodDrawButtonActionPerformed(evt);
            }
        });

        sheepDrawButton.setText("Sheep");
        sheepDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sheepDrawButtonActionPerformed(evt);
            }
        });

        brickDrawButton.setText("Brick");
        brickDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brickDrawButtonActionPerformed(evt);
            }
        });

        rockDrawButton.setText("Rock");
        rockDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockDrawButtonActionPerformed(evt);
            }
        });

        wheatDrawButton.setText("Wheat");
        wheatDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheatDrawButtonActionPerformed(evt);
            }
        });

        devCardDrawButton.setText("Development Card");
        devCardDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devCardDrawButtonActionPerformed(evt);
            }
        });

        turnCheckBox.setText("My Turn");
        turnCheckBox.setEnabled(false);

        statsOfPlayers.setText("Get Stats of Others");

        changeDrawButton.setText("Remove");
        changeDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDrawButtonActionPerformed(evt);
            }
        });

        rollDiceButton.setText("Roll Dice");
        rollDiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollDiceButtonActionPerformed(evt);
            }
        });

        dieRollOne.setText("1");

        dieRollTwo.setText("1");

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanelLayout.createSequentialGroup()
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turnCheckBox)
                    .addGroup(cardPanelLayout.createSequentialGroup()
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rollDiceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(woodLogoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(woodDrawButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardPanelLayout.createSequentialGroup()
                                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sheepLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sheepDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(brickLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(brickDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rockDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(rockLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(wheatLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(wheatDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addGroup(cardPanelLayout.createSequentialGroup()
                                .addComponent(dieRollOne, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dieRollTwo)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(devCardDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statsOfPlayers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeDrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(devCardLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(woodLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sheepLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brickLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rockLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wheatLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devCardLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(woodDrawButton)
                    .addComponent(sheepDrawButton)
                    .addComponent(brickDrawButton)
                    .addComponent(rockDrawButton)
                    .addComponent(wheatDrawButton)
                    .addComponent(devCardDrawButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turnCheckBox)
                    .addComponent(changeDrawButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsOfPlayers)
                    .addComponent(rollDiceButton)
                    .addComponent(dieRollOne)
                    .addComponent(dieRollTwo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chatLogScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nextTurnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sendMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(chatTextFieldScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mapPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(chatLogScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatTextFieldScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendMessageButton)
                            .addComponent(nextTurnButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brickDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brickDrawButtonActionPerformed
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(2);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }//GEN-LAST:event_brickDrawButtonActionPerformed

    private void woodDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_woodDrawButtonActionPerformed
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(0);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }//GEN-LAST:event_woodDrawButtonActionPerformed

    private void sheepDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sheepDrawButtonActionPerformed
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(1);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }//GEN-LAST:event_sheepDrawButtonActionPerformed

    private void rockDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockDrawButtonActionPerformed
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(3);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }//GEN-LAST:event_rockDrawButtonActionPerformed

    private void wheatDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheatDrawButtonActionPerformed
        Request theRequest = new Request();
        theRequest.setRequest(draw ? 3 : 4);
        theRequest.setType(4);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }//GEN-LAST:event_wheatDrawButtonActionPerformed

    private void devCardDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devCardDrawButtonActionPerformed
        Request theRequest = new Request();
        theRequest.setRequest(1);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }//GEN-LAST:event_devCardDrawButtonActionPerformed

    private void changeDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDrawButtonActionPerformed
        draw = !draw;
        // TODO add your handling code here:
    }//GEN-LAST:event_changeDrawButtonActionPerformed

    private void nextTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnButtonActionPerformed
        Request theRequest = new Request();
        theRequest.setRequest(5);
        sendRequest(theRequest);
        // TODO add your handling code here:
    }//GEN-LAST:event_nextTurnButtonActionPerformed

    private void rollDiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollDiceButtonActionPerformed
        Request theRequest = new Request();
        theRequest.setRequest(2);
        sendRequest(theRequest);        
        // TODO add your handling code here:
    }//GEN-LAST:event_rollDiceButtonActionPerformed

    private void sendRequest(Request request) {
        client.sendRequest(request);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientSideGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brickDrawButton;
    private javax.swing.JPanel brickLogoPanel;
    private javax.swing.JLabel brickNumberLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JToggleButton changeDrawButton;
    private javax.swing.JTextArea chatLogPanel;
    private javax.swing.JScrollPane chatLogScrollPane;
    private javax.swing.JTextArea chatTextField;
    private javax.swing.JScrollPane chatTextFieldScrollPane;
    private javax.swing.JButton devCardDrawButton;
    private javax.swing.JPanel devCardLogoPanel;
    private javax.swing.JLabel devCardNumberLabel;
    private javax.swing.JLabel dieRollOne;
    private javax.swing.JLabel dieRollTwo;
    private javax.swing.JPanel hex0;
    private javax.swing.JPanel hex1;
    private javax.swing.JPanel hex10;
    private javax.swing.JPanel hex11;
    private javax.swing.JPanel hex12;
    private javax.swing.JPanel hex13;
    private javax.swing.JPanel hex14;
    private javax.swing.JPanel hex15;
    private javax.swing.JPanel hex16;
    private javax.swing.JPanel hex17;
    private javax.swing.JPanel hex18;
    private javax.swing.JPanel hex2;
    private javax.swing.JPanel hex3;
    private javax.swing.JPanel hex4;
    private javax.swing.JPanel hex5;
    private javax.swing.JPanel hex6;
    private javax.swing.JPanel hex7;
    private javax.swing.JPanel hex8;
    private javax.swing.JPanel hex9;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JButton nextTurnButton;
    private javax.swing.JButton rockDrawButton;
    private javax.swing.JPanel rockLogoPanel;
    private javax.swing.JLabel rockNumberLabel;
    private javax.swing.JButton rollDiceButton;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JButton sheepDrawButton;
    private javax.swing.JPanel sheepLogoPanel;
    private javax.swing.JLabel sheepNumberLabel;
    private javax.swing.JButton statsOfPlayers;
    private javax.swing.JCheckBox turnCheckBox;
    private javax.swing.JButton wheatDrawButton;
    private javax.swing.JPanel wheatLogoPanel;
    private javax.swing.JLabel wheatNumberLabel;
    private javax.swing.JButton woodDrawButton;
    private javax.swing.JPanel woodLogoPanel;
    private javax.swing.JLabel woodNumberLabel;
    // End of variables declaration//GEN-END:variables

    private JPanel[] allHexs = { hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7, hex8, hex9, hex10, hex11, hex12, hex13, hex14, hex15, hex16, hex17, hex18 };
//    For final production:
//     private PaintImage brickLogoPanel;
//     private PaintImage devCardLogoPanel;
//     private PaintImage rockLogoPanel;
//     private PaintImage sheepLogoPanel;
//     private PaintImage wheatLogoPanel;
//     private PaintImage woodLogoPanel;
//     private PaintImage hex0;
//     private PaintImage hex1;
//     private PaintImage hex2;
//     private PaintImage hex3;
//     private PaintImage hex4;
//     private PaintImage hex5;
//     private PaintImage hex6;
//     private PaintImage hex7;
//     private PaintImage hex8;
//     private PaintImage hex9;
//     private PaintImage hex10;
//     private PaintImage hex11;
//     private PaintImage hex12;
//     private PaintImage hex13;
//     private PaintImage hex14;
//     private PaintImage hex15;
//     private PaintImage hex16;
//     private PaintImage hex17;
//     private PaintImage hex18;
//     private PaintImage[] allHexs = { hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7, hex8, hex9, hex10, hex11, hex12, hex13, hex14, hex15, hex16, hex17, hex18 };
//     
    
    
}

//class PaintImage extends JPanel {
//	
//  public BufferedImage image; 
//  
//  public PaintImage() {
//	  image = null;
//  }
//  
//  public PaintImage (String imageName) 
//  { 
//    super(); 
//    try 
//    {                
//      image = ImageIO.read(new File(imageName)); 
//    } 
//    catch (IOException e) 
//    { 
//    	System.out.println("Fail.");
//      //Not handled.
//    }
//  }
//
//  public void setImage(String filename) {
//	  try { image = ImageIO.read(new File(filename)); }
//	  catch (Exception e) { System.out.println("Fail."); }
//  }
//  
//  public void paintComponent(Graphics g) 
//  {
//    g.drawImage(image, 0, 0, null); 
//    repaint(); 
//  }
//  
//
//}